services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    # Mount the root directory
    volumes:
      - .:/usr/src/app
    # Overide the CMD to start dev server
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
  mongo-auth:
    image: mongo

  patients:
    build:
      context: .
      dockerfile: ./apps/patients/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    command: npm run start:dev patients
    env_file:
      - ./apps/patients/.env
    ports:
      - '3003:3003'
  mongo-patients:
    image: mongo

  predictions:
    build:
      context: .
      dockerfile: ./apps/predictions/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    command: npm run start:dev predictions
    env_file:
      - ./apps/predictions/.env
    ports:
      - '3005:3005'
  mongo-predictions:
    image: mongo
