services:
  mongo-trytumor:
    image: mongo

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3000:3000'

  # patients:
  #   build:
  #     context: .
  #     dockerfile: ./apps/patients/Dockerfile
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #   command: npm run start:dev patients
  #   env_file:
  #     - ./.env
  #   ports:
  #     - '3003:3003'

  # predictions:
  #   build:
  #     context: .
  #     dockerfile: ./apps/predictions/Dockerfile
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #   command: npm run start:dev predictions
  #   env_file:
  #     - ./.env
  #   ports:
  #     - '3005:3005'
