services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    # Mount the root directory
    volumes:
      - .:/usr/src/app
    # Overide the CMD to start dev server
    command: npm run test:e2e:auth
    env_file:
      - ./apps/auth/.env.test
    ports:
      - '3001:3001'
  mongo-auth:
    image: mongo

  patients:
    build:
      context: .
      dockerfile: ./apps/patients/Dockerfile
    volumes:
      - .:/usr/src/app
    command: npm run test:e2e:patients
    env_file:
      - ./apps/patients/.env.test
    ports:
      - '3003:3003'
  mongo-patients:
    image: mongo

  predictions:
    build:
      context: .
      dockerfile: ./apps/predictions/Dockerfile
    volumes:
      - .:/usr/src/app
    command: npm run test:e2e:predictions
    env_file:
      - ./apps/predictions/.env.test
    ports:
      - '3005:3005'
  mongo-predictions:
    image: mongo
