object_admin_sa_key: projects/480588714013/secrets/dev-object-admin-sa-key/versions/latest
jwt_secret: projects/480588714013/secrets/dev-config-jwt-secret/versions/latest
jwt_refresh_secret: projects/480588714013/secrets/dev-config-jwt-refresh-secret/versions/latest
jwt_testing_secret: projects/480588714013/secrets/dev-config-jwt-testing-secret/versions/latest
jwt_expiration: projects/480588714013/secrets/dev-config-jwt-expiration/versions/latest
jwt_refresh_expiration: projects/480588714013/secrets/dev-config-jwt-refresh-expiration/versions/latest