object_admin_sa_key: projects/480588714013/secrets/dev-object-admin-sa-key/versions/latest
pubsub_admin_sa_key: projects/480588714013/secrets/dev-pubsub-admin-sa-key/versions/latest
jwt_secret: projects/480588714013/secrets/dev-config-jwt-secret/versions/latest